lande='<SELECT NAME="country">'+
'<OPTION VALUE="00">'+
'<OPTION VALUE="AF">Afghanistan'+
'<OPTION VALUE="AL">Albanië'+
'<OPTION VALUE="DZ">Algerije'+
'<OPTION VALUE="AS">Amerikaans-Samoa'+
'<OPTION VALUE="VI">Amerikaanse Maagdeneilanden'+
'<OPTION VALUE="UM">Amerikaanse ondergeschikte afgelegen eilanden'+
'<OPTION VALUE="AD">Andorra'+
'<OPTION VALUE="AO">Angola'+
'<OPTION VALUE="AI">Anguilla'+
'<OPTION VALUE="AQ">Antarctica'+
'<OPTION VALUE="AG">Antigua en Barbuda'+
'<OPTION VALUE="AR">Argentinië'+
'<OPTION VALUE="AM">Armenië'+
'<OPTION VALUE="AW">Aruba'+
'<OPTION VALUE="AU">Australië'+
'<OPTION VALUE="AZ">Azerbeidzjan'+
'<OPTION VALUE="BS">Bahama\'s'+
'<OPTION VALUE="BH">Bahrein'+
'<OPTION VALUE="BD">Bangladesh'+
'<OPTION VALUE="BB">Barbados'+
'<OPTION VALUE="BY">Belarus'+
'<OPTION VALUE="BE">België'+
'<OPTION VALUE="BZ">Belize'+
'<OPTION VALUE="BJ">Benin'+
'<OPTION VALUE="BM">Bermuda'+
'<OPTION VALUE="BT">Bhutan'+
'<OPTION VALUE="BO">Bolivia'+
'<OPTION VALUE="BA">Bosnië en Herzegovina'+
'<OPTION VALUE="BW">Botswana'+
'<OPTION VALUE="BV">Bouveteiland'+
'<OPTION VALUE="BR">Brazilië'+
'<OPTION VALUE="IO">Brits Territorium in de Indische Oceaan'+
'<OPTION VALUE="VG">Britse Maagdeneilanden'+
'<OPTION VALUE="BN">Brunei Darussalam'+
'<OPTION VALUE="BG">Bulgarije'+
'<OPTION VALUE="BF">Burkina Faso'+
'<OPTION VALUE="BI">Burundi'+
'<OPTION VALUE="KH">Cambodja'+
'<OPTION VALUE="CA">Canada'+
'<OPTION VALUE="KY">Caymaneilanden'+
'<OPTION VALUE="CF">Centraal-Afrikaanse Republiek'+
'<OPTION VALUE="CL">Chili'+
'<OPTION VALUE="CN">China'+
'<OPTION VALUE="CX">Christmaseiland'+
'<OPTION VALUE="CC">Cocoseilanden (Keeling)'+
'<OPTION VALUE="CO">Colombia'+
'<OPTION VALUE="KM">Comoren'+
'<OPTION VALUE="CG">Congo'+
'<OPTION VALUE="CK">Cookeilanden'+
'<OPTION VALUE="CR">Costa Rica'+
'<OPTION VALUE="CU">Cuba'+
'<OPTION VALUE="CY">Cyprus'+
'<OPTION VALUE="DK">Denemarken'+
'<OPTION VALUE="DJ">Djibouti'+
'<OPTION VALUE="DM">Dominica'+
'<OPTION VALUE="DO">Dominicaanse Republiek'+
'<OPTION VALUE="DE">Duitsland'+
'<OPTION VALUE="EC">Ecuador'+
'<OPTION VALUE="EG">Egypte'+
'<OPTION VALUE="SV">El Salvador'+
'<OPTION VALUE="GQ">Equatoriaal-Guinea'+
'<OPTION VALUE="ER">Eritrea'+
'<OPTION VALUE="EE">Estland'+
'<OPTION VALUE="ET">Ethiopië'+
'<OPTION VALUE="FO">Faeröer'+
'<OPTION VALUE="FK">Falklandeilanden'+
'<OPTION VALUE="FJ">Fiji'+
'<OPTION VALUE="PH">Filippijnen'+
'<OPTION VALUE="FI">Finland'+
'<OPTION VALUE="FR">Frankrijk'+
'<OPTION VALUE="GF">Frans-Guyana'+
'<OPTION VALUE="PF">Frans-Polynesië'+
'<OPTION VALUE="TF">Franse Gebieden in de zuidelijke Indische Oceaan'+
'<OPTION VALUE="GA">Gabon'+
'<OPTION VALUE="GM">Gambia'+
'<OPTION VALUE="GE">Georgië'+
'<OPTION VALUE="GH">Ghana'+
'<OPTION VALUE="GI">Gibraltar'+
'<OPTION VALUE="GD">Grenada'+
'<OPTION VALUE="GR">Griekenland'+
'<OPTION VALUE="GL">Groenland'+
'<OPTION VALUE="GP">Guadeloupe'+
'<OPTION VALUE="GU">Guam'+
'<OPTION VALUE="GT">Guatemala'+
'<OPTION VALUE="GW">Guinea-Bissau'+
'<OPTION VALUE="GN">Guinee'+
'<OPTION VALUE="GY">Guyana'+
'<OPTION VALUE="HT">Haïti'+
'<OPTION VALUE="HM">Heard- en McDonaldeilanden'+
'<OPTION VALUE="HN">Honduras'+
'<OPTION VALUE="HU">Hongarije'+
'<OPTION VALUE="HK">Hongkong'+
'<OPTION VALUE="IE">Ierland'+
'<OPTION VALUE="IS">IJsland'+
'<OPTION VALUE="IN">India'+
'<OPTION VALUE="ID">Indonesië'+
'<OPTION VALUE="IQ">Irak'+
'<OPTION VALUE="IR">Iran'+
'<OPTION VALUE="IL">Israël'+
'<OPTION VALUE="IT">Italië'+
'<OPTION VALUE="CI">Ivoorkust'+
'<OPTION VALUE="JM">Jamaica'+
'<OPTION VALUE="JP">Japan'+
'<OPTION VALUE="YE">Jemen'+
'<OPTION VALUE="YU">Joegoslavië'+
'<OPTION VALUE="JO">Jordanië'+
'<OPTION VALUE="CV">Kaapverdië'+
'<OPTION VALUE="CM">Kameroen'+
'<OPTION VALUE="KZ">Kazakstan'+
'<OPTION VALUE="KE">Kenya'+
'<OPTION VALUE="KG">Kirgistan'+
'<OPTION VALUE="KI">Kiribati'+
'<OPTION VALUE="KW">Koewait'+
'<OPTION VALUE="HR">Kroatië'+
'<OPTION VALUE="LA">Laos'+
'<OPTION VALUE="LS">Lesotho'+
'<OPTION VALUE="LV">Letland'+
'<OPTION VALUE="LB">Libanon'+
'<OPTION VALUE="LR">Liberia'+
'<OPTION VALUE="LY">Libisch-Arabische Jamahiriya'+
'<OPTION VALUE="LI">Liechtenstein'+
'<OPTION VALUE="LT">Litouwen'+
'<OPTION VALUE="LU">Luxemburg'+
'<OPTION VALUE="MO">Macau'+
'<OPTION VALUE="MK">Macedonië (FYR)'+
'<OPTION VALUE="MG">Madagaskar'+
'<OPTION VALUE="MW">Malawi'+
'<OPTION VALUE="MV">Maldiven'+
'<OPTION VALUE="MY">Maleisië'+
'<OPTION VALUE="ML">Mali'+
'<OPTION VALUE="MT">Malta'+
'<OPTION VALUE="MA">Marokko'+
'<OPTION VALUE="MH">Marshalleilanden'+
'<OPTION VALUE="MQ">Martinique'+
'<OPTION VALUE="MR">Mauritanië'+
'<OPTION VALUE="MU">Mauritius'+
'<OPTION VALUE="YT">Mayotte'+
'<OPTION VALUE="MX">Mexico'+
'<OPTION VALUE="FM">Micronesia'+
'<OPTION VALUE="MD">Moldavië'+
'<OPTION VALUE="MC">Monaco'+
'<OPTION VALUE="MN">Mongolië'+
'<OPTION VALUE="MS">Montserrat'+
'<OPTION VALUE="MZ">Mozambique'+
'<OPTION VALUE="MM">Myanmar'+
'<OPTION VALUE="NA">Namibië'+
'<OPTION VALUE="NR">Nauru'+
'<OPTION selected VALUE="NL">Nederland'+
'<OPTION VALUE="AN">Nederlandse Antillen'+
'<OPTION VALUE="NP">Nepal'+
'<OPTION VALUE="NI">Nicaragua'+
'<OPTION VALUE="NC">Nieuw-Caledonië'+
'<OPTION VALUE="NZ">Nieuw-Zeeland'+
'<OPTION VALUE="NE">Niger'+
'<OPTION VALUE="NG">Nigeria'+
'<OPTION VALUE="NU">Niue'+
'<OPTION VALUE="KP">Noord-Korea'+
'<OPTION VALUE="MP">Noordelijke Marianen'+
'<OPTION VALUE="NO">Noorwegen'+
'<OPTION VALUE="NF">Norfolkeiland'+
'<OPTION VALUE="UG">Oeganda'+
'<OPTION VALUE="UA">Oekraïne'+
'<OPTION VALUE="UZ">Oezbekistan'+
'<OPTION VALUE="OM">Oman'+
'<OPTION VALUE="TP">Oost-Timor'+
'<OPTION VALUE="AT">Oostenrijk'+
'<OPTION VALUE="PK">Pakistan'+
'<OPTION VALUE="PW">Palau'+
'<OPTION VALUE="PS">Palestijnse bezette gebieden'+
'<OPTION VALUE="PA">Panama'+
'<OPTION VALUE="PG">Papoea-Nieuw-Guinea'+
'<OPTION VALUE="PY">Paraguay'+
'<OPTION VALUE="PE">Peru'+
'<OPTION VALUE="PN">Pitcairneilanden'+
'<OPTION VALUE="PL">Polen'+
'<OPTION VALUE="PT">Portugal'+
'<OPTION VALUE="PR">Puerto Rico'+
'<OPTION VALUE="QA">Qatar'+
'<OPTION VALUE="RO">Roemenië'+
'<OPTION VALUE="RU">Russische Federatie'+
'<OPTION VALUE="RW">Rwanda'+
'<OPTION VALUE="RE">Réunion'+
'<OPTION VALUE="SH">Saint Helena'+
'<OPTION VALUE="KN">Saint Kitts en Nevis'+
'<OPTION VALUE="LC">Saint Lucia'+
'<OPTION VALUE="PM">Saint Pierre en Miquelon'+
'<OPTION VALUE="VC">Saint Vincent en de Grenadines'+
'<OPTION VALUE="SB">Salomonseilanden'+
'<OPTION VALUE="WS">Samoa'+
'<OPTION VALUE="SM">San Marino'+
'<OPTION VALUE="ST">Sao Tomé en Principe'+
'<OPTION VALUE="SA">Saudi-Arabië'+
'<OPTION VALUE="SN">Senegal'+
'<OPTION VALUE="SC">Seychellen'+
'<OPTION VALUE="SL">Sierra Leone'+
'<OPTION VALUE="SG">Singapore'+
'<OPTION VALUE="SI">Slovenië'+
'<OPTION VALUE="SK">Slowakije'+
'<OPTION VALUE="SO">Somalië'+
'<OPTION VALUE="ES">Spanje'+
'<OPTION VALUE="LK">Sri Lanka'+
'<OPTION VALUE="SD">Sudan'+
'<OPTION VALUE="SR">Suriname'+
'<OPTION VALUE="SJ">Svalbard en Jan Mayen'+
'<OPTION VALUE="SZ">Swaziland'+
'<OPTION VALUE="SY">Syrië'+
'<OPTION VALUE="TJ">Tadzjikistan'+
'<OPTION VALUE="TW">Taiwan'+
'<OPTION VALUE="TZ">Tanzania'+
'<OPTION VALUE="TH">Thailand'+
'<OPTION VALUE="TG">Togo'+
'<OPTION VALUE="TK">Tokelau-eilanden'+
'<OPTION VALUE="TO">Tonga'+
'<OPTION VALUE="TT">Trinidad en Tobago'+
'<OPTION VALUE="TD">Tsjaad'+
'<OPTION VALUE="CZ">Tsjechische Republiek'+
'<OPTION VALUE="TN">Tunesië'+
'<OPTION VALUE="TR">Turkije'+
'<OPTION VALUE="TM">Turkmenistan'+
'<OPTION VALUE="TC">Turks- en Caicoseilanden'+
'<OPTION VALUE="TV">Tuvalu'+
'<OPTION VALUE="UY">Uruguay'+
'<OPTION VALUE="VU">Vanuatu'+
'<OPTION VALUE="VA">Vaticaanstad'+
'<OPTION VALUE="VE">Venezuela'+
'<OPTION VALUE="GB">Verenigd Koninkrijk'+
'<OPTION VALUE="AE">Verenigde Arabische Emiraten'+
'<OPTION VALUE="US">Verenigde Staten'+
'<OPTION VALUE="VN">Viet Nam'+
'<OPTION VALUE="WF">Wallis en Futuna'+
'<OPTION VALUE="EH">Westelijke Sahara'+
'<OPTION VALUE="ZM">Zambia'+
'<OPTION VALUE="ZR">Zaïre'+
'<OPTION VALUE="ZW">Zimbabwe'+
'<OPTION VALUE="ZA">Zuid-Afrika'+
'<OPTION VALUE="GS">Zuid-Georgië'+
'<OPTION VALUE="KR">Zuid-Korea'+
'<OPTION VALUE="SE">Zweden'+
'<OPTION VALUE="CH">Zwitserland';
document.write(lande);
